### PR TITLE
[AB][116162145] Load warehouse image pixel outside of DOM

### PR DESCRIPTION
**Pull request by aribouius**
The code was attempting to append the warehouse image pixel into the DOM before the DOM was ready for inspection (e.g. `DOMContentLoaded` event).  This change removes the need to wait for the DOM ready event by creating a new image outside the DOM context.

https://www.pivotaltracker.com/story/show/116162145

### CODE REVIEW

**Comment by Teapane** [comment]
:+1: LGTM

**Comment by martinstreicher** [comment]
Should this be a feat or a fix?

**Comment by Teapane** [comment]
@martinstreicher does your branch need to be merged first in order for the dist files to be built correctly?

**Comment by aribouius** [comment]
@martinstreicher it should be a fix. I'll correct the commit message.

**Comment by martinstreicher** [comment]
Yes.

**Pull request merged**
